openapi: 3.1.0
info:
  title: V2EX
  description: ''
  version: 1.0.0
tags: []
paths:
  /topics/{topic_id}:
    get:
      summary: 获取指定主题
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: topic_id
          in: path
          description: ''
          required: true
          example: '1146865'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  result:
                    properties:
                      id:
                        type: integer
                      title:
                        type: string
                      content:
                        type: string
                      content_rendered:
                        type: string
                      syntax:
                        type: integer
                      url:
                        type: string
                      replies:
                        type: integer
                      last_reply_by:
                        type: string
                      created:
                        type: integer
                      last_modified:
                        type: integer
                      last_touched:
                        type: integer
                      member:
                        type: object
                        properties:
                          id:
                            type: integer
                          username:
                            type: string
                          bio:
                            type: string
                          website:
                            type: string
                          github:
                            type: string
                          url:
                            type: string
                          avatar:
                            type: string
                          created:
                            type: integer
                          pro:
                            type: integer
                        required:
                          - id
                          - username
                          - bio
                          - website
                          - github
                          - url
                          - avatar
                          - created
                          - pro
                      node:
                        type: object
                        properties:
                          id:
                            type: integer
                          url:
                            type: string
                          name:
                            type: string
                          title:
                            type: string
                          header:
                            type: string
                          footer:
                            type: string
                          avatar:
                            type: string
                          topics:
                            type: integer
                          created:
                            type: integer
                          last_modified:
                            type: integer
                        required:
                          - id
                          - url
                          - name
                          - title
                          - header
                          - footer
                          - avatar
                          - topics
                          - created
                          - last_modified
                      supplements:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            content:
                              type: string
                            content_rendered:
                              type: string
                            syntax:
                              type: integer
                            created:
                              type: integer
                    required:
                      - id
                      - title
                      - content
                      - content_rendered
                      - syntax
                      - url
                      - replies
                      - last_reply_by
                      - created
                      - last_modified
                      - last_touched
                      - member
                      - node
                      - supplements
                    $ref: '#/components/schemas/topic'
                required:
                  - success
                  - message
                  - result
              example:
                success: true
                message: Topic details found
                result:
                  id: 1146865
                  title: 20250721 - Solana 原生代币 SOL 打赏
                  content: "基于 Solana 原生代币的社区内打赏功能已经在 V2EX 部署。\r\n\r\n目前你可以在用户个人主页的桌面版本找到打赏按钮，比如这是我的主页，上面就可以看到打赏按钮：\r\n\r\nhttps://www.v2ex.com/member/Livid\r\n\r\n如果你希望在 V2EX 接受 Solana 打赏，可以在设置中绑定自己的 Solana 钱包地址：\r\n\r\nhttps://www.v2ex.com/settings/crypto\r\n\r\n接下来，这个按钮的功能会扩展到手机版本页面及主题页面。\r\n\r\n这里可以看到自己收到和发出的所有打赏记录：\r\n\r\nhttps://www.v2ex.com/solana/tips\r\n\r\n目前支持的是使用 Solana 原生代币 SOL 直接打赏。使用的是最简单的 transfer 方式，所有数额会 100% 进入被打赏用户的钱包，V2EX 只是提供界面和记录，不收取任何中间费用。\r\n\r\n对于很多初次使用 Solana 的用户，相信这会成为他们获得第一笔 gas 费的来源。\r\n\r\n后续会扩展支持其他 SPL Token 。"
                  content_rendered: >-
                    基于 Solana 原生代币的社区内打赏功能已经在 V2EX 部署。<br /><br
                    />目前你可以在用户个人主页的桌面版本找到打赏按钮，比如这是我的主页，上面就可以看到打赏按钮：<br /><br
                    /><a target="_blank"
                    href="https://www.v2ex.com/member/Livid" rel="nofollow
                    noopener">https://www.v2ex.com/member/Livid</a><br /><br
                    />如果你希望在 V2EX 接受 Solana 打赏，可以在设置中绑定自己的 Solana 钱包地址：<br /><br
                    /><a target="_blank"
                    href="https://www.v2ex.com/settings/crypto" rel="nofollow
                    noopener">https://www.v2ex.com/settings/crypto</a><br /><br
                    />接下来，这个按钮的功能会扩展到手机版本页面及主题页面。<br /><br
                    />这里可以看到自己收到和发出的所有打赏记录：<br /><br /><a target="_blank"
                    href="https://www.v2ex.com/solana/tips" rel="nofollow
                    noopener">https://www.v2ex.com/solana/tips</a><br /><br
                    />目前支持的是使用 Solana 原生代币 SOL 直接打赏。使用的是最简单的 transfer 方式，所有数额会
                    100% 进入被打赏用户的钱包，V2EX 只是提供界面和记录，不收取任何中间费用。<br /><br
                    />对于很多初次使用 Solana 的用户，相信这会成为他们获得第一笔 gas 费的来源。<br /><br
                    />后续会扩展支持其他 SPL Token 。
                  syntax: 0
                  url: https://www.v2ex.com/t/1146865
                  replies: 711
                  last_reply_by: ik
                  created: 1753163305
                  last_modified: 1753163305
                  last_touched: 1753371501
                  member:
                    id: 1
                    username: Livid
                    bio: ''
                    website: sepia.sol.build
                    github: ''
                    url: https://www.v2ex.com/member/Livid
                    avatar: >-
                      https://cdn.v2ex.com/avatar/c4ca/4238/1_xxxlarge.png?m=1753359717
                    created: 1272203146
                    pro: 1753519572
                  node:
                    id: 850
                    url: https://www.v2ex.com/go/status
                    name: status
                    title: V2EX 站点状态
                    header: 关于 V2EX 的网站状态和功能更新的最新公告
                    footer: ''
                    avatar: >-
                      https://cdn.v2ex.com/navatar/1efa/39bc/850_xxlarge.png?m=1633041301
                    topics: 39
                    created: 1431698784
                    last_modified: 1633041301
                  supplements:
                    - id: 190767
                      content: "## 功能更新 1\r\n\r\n在查看其他 V2EX 用户的个人主页时，现在可以看到你和这个用户的打赏交互记录。"
                      content_rendered: |
                        <h2>功能更新 1</h2>
                        <p>在查看其他 V2EX 用户的个人主页时，现在可以看到你和这个用户的打赏交互记录。</p>
                      syntax: 1
                      created: 1753214592
          headers: {}
      security:
        - token: []
  /topics/{topic_id}/replies:
    get:
      summary: 获取指定主题下的回复
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: topic_id
          in: path
          description: ''
          required: true
          example: '1146865'
          schema:
            type: string
        - name: p
          in: query
          description: ''
          required: false
          example: '1'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  result:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
                        content_rendered:
                          type: string
                        created:
                          type: integer
                        member:
                          type: object
                          properties:
                            id:
                              type: integer
                            username:
                              type: string
                            bio:
                              type:
                                - string
                                - 'null'
                            website:
                              type:
                                - string
                                - 'null'
                            github:
                              type:
                                - string
                                - 'null'
                            url:
                              type: string
                            avatar:
                              type: string
                            created:
                              type: integer
                            pro:
                              type: integer
                          required:
                            - id
                            - username
                            - bio
                            - website
                            - github
                            - url
                            - avatar
                            - created
                            - pro
                      required:
                        - id
                        - content
                        - content_rendered
                        - created
                        - member
                      $ref: '#/components/schemas/reply'
                  pagination:
                    type: object
                    properties:
                      per_page:
                        type: integer
                      total:
                        type: integer
                      pages:
                        type: integer
                    required:
                      - per_page
                      - total
                      - pages
                required:
                  - success
                  - message
                  - result
                  - pagination
              example:
                success: true
                message: Topic replies found
                result:
                  - id: 16517393
                    content: 有人打赏我一下看看功能好用不 https://i.imgur.com/duWRpIu.png
                    content_rendered: >-
                      有人打赏我一下看看功能好用不 <a target="_blank"
                      href="https://i.imgur.com/duWRpIu.png" rel="nofollow
                      noopener" target="_blank"><img
                      src="https://i.imgur.com/duWRpIu.png"
                      class="embedded_image" rel="noreferrer"></a>
                    created: 1753163434
                    member:
                      id: 13344
                      username: Ansen
                      bio: ''
                      website: ''
                      github: ''
                      url: https://www.v2ex.com/member/Ansen
                      avatar: >-
                        https://cdn.v2ex.com/avatar/d481/fbe5/13344_xxlarge.png?m=1740894695
                      created: 1320460634
                      pro: 0
                  - id: 16517408
                    content: 我也想试试 感觉很好玩，有人打赏我吗？一毛钱也行试试是啥样
                    content_rendered: 我也想试试 感觉很好玩，有人打赏我吗？一毛钱也行试试是啥样
                    created: 1753163645
                    member:
                      id: 586523
                      username: littleJohn
                      bio: null
                      website: null
                      github: null
                      url: https://www.v2ex.com/member/littleJohn
                      avatar: >-
                        https://cdn.v2ex.com/gravatar/0c1ee942c8415f341f9fb0790c749fd2?s=73&d=retro
                      created: 1656687084
                      pro: 0
                  - id: 16517409
                    content: 要是钱包能链接到币安就好了
                    content_rendered: 要是钱包能链接到币安就好了
                    created: 1753163655
                    member:
                      id: 582231
                      username: liu731
                      bio: ''
                      website: ''
                      github: null
                      url: https://www.v2ex.com/member/liu731
                      avatar: >-
                        https://cdn.v2ex.com/avatar/6159/9999/582231_xxxlarge.png?m=1752114640
                      created: 1653028486
                      pro: 0
                  - id: 16517419
                    content: 看来马上就可以打赏 $v2ex 了
                    content_rendered: 看来马上就可以打赏 $v2ex 了
                    created: 1753163746
                    member:
                      id: 71485
                      username: hackerwgf
                      bio: ''
                      website: ''
                      github: hackerwgf
                      url: https://www.v2ex.com/member/hackerwgf
                      avatar: >-
                        https://cdn.v2ex.com/avatar/4345/29ee/71485_large.png?m=1752751767
                      created: 1408547348
                      pro: 1753495093
                  - id: 16517432
                    content: Phantom 会提示不安全
                    content_rendered: Phantom 会提示不安全
                    created: 1753163814
                    member:
                      id: 365763
                      username: putaozhenhaochi
                      bio: ''
                      website: ''
                      github: ''
                      url: https://www.v2ex.com/member/putaozhenhaochi
                      avatar: >-
                        https://cdn.v2ex.com/avatar/aa58/d4b1/365763_large.png?m=1613284187
                      created: 1543208509
                      pro: 0
                  - id: 16517435
                    content: 竟然不是 V2EX 币独占，格局还是大啊。
                    content_rendered: 竟然不是 V2EX 币独占，格局还是大啊。
                    created: 1753163878
                    member:
                      id: 439711
                      username: cmdOptionKana
                      bio: ''
                      website: ''
                      github: ''
                      url: https://www.v2ex.com/member/cmdOptionKana
                      avatar: >-
                        https://cdn.v2ex.com/avatar/07c9/d6c7/439711_large.png?m=1715166908
                      created: 1567591320
                      pro: 0
                  - id: 16517440
                    content: 已经关联钱包了，就等各位大佬的打赏了。感兴趣的可以点击头像，到个人主页进行打赏～ （让在线乞讨，成为可能）
                    content_rendered: 已经关联钱包了，就等各位大佬的打赏了。感兴趣的可以点击头像，到个人主页进行打赏～ （让在线乞讨，成为可能）
                    created: 1753163901
                    member:
                      id: 143695
                      username: jiandao7114
                      bio: ''
                      website: ''
                      github: null
                      url: https://www.v2ex.com/member/jiandao7114
                      avatar: >-
                        https://cdn.v2ex.com/gravatar/4f0bcdb7ae9f06298769e4c7ca1aaf15?s=73&d=retro
                      created: 1445419296
                      pro: 0
                  - id: 16517441
                    content: "@littleJohn 你需要先连接地址。\r\n\r\nhttps://www.v2ex.com/solana"
                    content_rendered: >-
                      @<a href="/member/littleJohn">littleJohn</a> 你需要先连接地址。<br
                      /><br /><a target="_blank"
                      href="https://www.v2ex.com/solana" rel="nofollow
                      noopener">https://www.v2ex.com/solana</a>
                    created: 1753163911
                    member:
                      id: 1
                      username: Livid
                      bio: ''
                      website: sepia.sol.build
                      github: ''
                      url: https://www.v2ex.com/member/Livid
                      avatar: >-
                        https://cdn.v2ex.com/avatar/c4ca/4238/1_xxxlarge.png?m=1753359717
                      created: 1272203146
                      pro: 1753519572
                  - id: 16517444
                    content: '@putaozhenhaochi 可以发一个截图吗？'
                    content_rendered: >-
                      @<a href="/member/putaozhenhaochi">putaozhenhaochi</a>
                      可以发一个截图吗？
                    created: 1753163951
                    member:
                      id: 1
                      username: Livid
                      bio: ''
                      website: sepia.sol.build
                      github: ''
                      url: https://www.v2ex.com/member/Livid
                      avatar: >-
                        https://cdn.v2ex.com/avatar/c4ca/4238/1_xxxlarge.png?m=1753359717
                      created: 1272203146
                      pro: 1753519572
                  - id: 16517447
                    content: "@Ansen \r\n@jiandao7114 \r\n\r\nSent!"
                    content_rendered: >-
                      @<a href="/member/Ansen">Ansen</a> <br />@<a
                      href="/member/jiandao7114">jiandao7114</a> <br /><br
                      />Sent!
                    created: 1753163965
                    member:
                      id: 1
                      username: Livid
                      bio: ''
                      website: sepia.sol.build
                      github: ''
                      url: https://www.v2ex.com/member/Livid
                      avatar: >-
                        https://cdn.v2ex.com/avatar/c4ca/4238/1_xxxlarge.png?m=1753359717
                      created: 1272203146
                      pro: 1753519572
                  - id: 16517450
                    content: 已经关联钱包了+1 看看会不会有打赏~
                    content_rendered: 已经关联钱包了+1 看看会不会有打赏~
                    created: 1753163995
                    member:
                      id: 84747
                      username: suhu
                      bio: ''
                      website: ''
                      github: ''
                      url: https://www.v2ex.com/member/suhu
                      avatar: >-
                        https://cdn.v2ex.com/avatar/1aaa/be7d/84747_xxxlarge.png?m=1734252323
                      created: 1417482589
                      pro: 0
                  - id: 16517458
                    content: '@cmdOptionKana 我觉得这是对用户和社区都更有价值的空投方式'
                    content_rendered: >-
                      @<a href="/member/cmdOptionKana">cmdOptionKana</a>
                      我觉得这是对用户和社区都更有价值的空投方式
                    created: 1753164033
                    member:
                      id: 1
                      username: Livid
                      bio: ''
                      website: sepia.sol.build
                      github: ''
                      url: https://www.v2ex.com/member/Livid
                      avatar: >-
                        https://cdn.v2ex.com/avatar/c4ca/4238/1_xxxlarge.png?m=1753359717
                      created: 1272203146
                      pro: 1753519572
                  - id: 16517460
                    content: >-
                      @Livid 可以考虑在信息页/甚至是回帖的昵称旁边直接显示$V2EX
                      的数量？可以作为一种“文化”亦或是“支持”的具体体现
                    content_rendered: >-
                      @<a href="/member/Livid">Livid</a>
                      可以考虑在信息页/甚至是回帖的昵称旁边直接显示$V2EX 的数量？可以作为一种“文化”亦或是“支持”的具体体现
                    created: 1753164058
                    member:
                      id: 84747
                      username: suhu
                      bio: ''
                      website: ''
                      github: ''
                      url: https://www.v2ex.com/member/suhu
                      avatar: >-
                        https://cdn.v2ex.com/avatar/1aaa/be7d/84747_xxxlarge.png?m=1734252323
                      created: 1417482589
                      pro: 0
                  - id: 16517461
                    content: 关联了看看
                    content_rendered: 关联了看看
                    created: 1753164065
                    member:
                      id: 371687
                      username: epicSoldier
                      bio: null
                      website: null
                      github: null
                      url: https://www.v2ex.com/member/epicSoldier
                      avatar: >-
                        https://cdn.v2ex.com/avatar/2db7/e5ee/371687_xxxlarge.png?m=1749114335
                      created: 1545273210
                      pro: 0
                  - id: 16517462
                    content: 已经关联钱包了+1 坐等打赏效果了
                    content_rendered: 已经关联钱包了+1 坐等打赏效果了
                    created: 1753164077
                    member:
                      id: 360672
                      username: AlecJi
                      bio: ''
                      website: ''
                      github: null
                      url: https://www.v2ex.com/member/AlecJi
                      avatar: >-
                        https://cdn.v2ex.com/gravatar/f62ff1fe1e04279c7295efd240c14b9c?s=73&d=retro
                      created: 1541252012
                      pro: 0
                  - id: 16517463
                    content: '@suhu 嗯，这个会在接下来小心设计。'
                    content_rendered: '@<a href="/member/suhu">suhu</a> 嗯，这个会在接下来小心设计。'
                    created: 1753164089
                    member:
                      id: 1
                      username: Livid
                      bio: ''
                      website: sepia.sol.build
                      github: ''
                      url: https://www.v2ex.com/member/Livid
                      avatar: >-
                        https://cdn.v2ex.com/avatar/c4ca/4238/1_xxxlarge.png?m=1753359717
                      created: 1272203146
                      pro: 1753519572
                  - id: 16517468
                    content: 哈哈哈哈。玩法多了起来，可以直接发布悬赏任务了。
                    content_rendered: 哈哈哈哈。玩法多了起来，可以直接发布悬赏任务了。
                    created: 1753164167
                    member:
                      id: 354938
                      username: weixind
                      bio: ''
                      website: https://langshift.dev
                      github: erweixin
                      url: https://www.v2ex.com/member/weixind
                      avatar: >-
                        https://cdn.v2ex.com/avatar/83d2/802a/354938_large.png?m=1751596523
                      created: 1539136477
                      pro: 0
                  - id: 16517474
                    content: '@weixind 这事感觉需要谨慎一点，包括交易类的，我觉得需要站长付出经历来应对各种投诉是很麻烦的事'
                    content_rendered: >-
                      @<a href="/member/weixind">weixind</a>
                      这事感觉需要谨慎一点，包括交易类的，我觉得需要站长付出经历来应对各种投诉是很麻烦的事
                    created: 1753164208
                    member:
                      id: 84747
                      username: suhu
                      bio: ''
                      website: ''
                      github: ''
                      url: https://www.v2ex.com/member/suhu
                      avatar: >-
                        https://cdn.v2ex.com/avatar/1aaa/be7d/84747_xxxlarge.png?m=1734252323
                      created: 1417482589
                      pro: 0
                  - id: 16517477
                    content: "@weixind \r\n\r\n嗯，这是接下来其他功能的基础架构。"
                    content_rendered: >-
                      @<a href="/member/weixind">weixind</a> <br /><br
                      />嗯，这是接下来其他功能的基础架构。
                    created: 1753164232
                    member:
                      id: 1
                      username: Livid
                      bio: ''
                      website: sepia.sol.build
                      github: ''
                      url: https://www.v2ex.com/member/Livid
                      avatar: >-
                        https://cdn.v2ex.com/avatar/c4ca/4238/1_xxxlarge.png?m=1753359717
                      created: 1272203146
                      pro: 1753519572
                  - id: 16517483
                    content: 玩法起来了，坐等打赏+1
                    content_rendered: 玩法起来了，坐等打赏+1
                    created: 1753164284
                    member:
                      id: 72848
                      username: bugsnail
                      bio: ''
                      website: ''
                      github: ''
                      url: https://www.v2ex.com/member/bugsnail
                      avatar: >-
                        https://cdn.v2ex.com/avatar/c491/561d/72848_xxxlarge.png?m=1738805042
                      created: 1409738543
                      pro: 0
                pagination:
                  per_page: 20
                  total: 711
                  pages: 36
          headers: {}
      security:
        - token: []
  /nodes/{node_name}:
    get:
      summary: 获取指定节点
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: node_name
          in: path
          description: ''
          required: true
          example: status
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  result:
                    type: object
                    properties:
                      id:
                        type: integer
                      url:
                        type: string
                      name:
                        type: string
                      title:
                        type: string
                      header:
                        type: string
                      footer:
                        type: string
                      avatar:
                        type: string
                      topics:
                        type: integer
                      created:
                        type: integer
                      last_modified:
                        type: integer
                    required:
                      - id
                      - url
                      - name
                      - title
                      - header
                      - footer
                      - avatar
                      - topics
                      - created
                      - last_modified
                    $ref: '#/components/schemas/node'
                required:
                  - success
                  - message
                  - result
              example:
                success: true
                message: Node details found
                result:
                  id: 850
                  url: https://www.v2ex.com/go/status
                  name: status
                  title: V2EX 站点状态
                  header: 关于 V2EX 的网站状态和功能更新的最新公告
                  footer: ''
                  avatar: >-
                    https://cdn.v2ex.com/navatar/1efa/39bc/850_xxlarge.png?m=1633041301
                  topics: 39
                  created: 1431698784
                  last_modified: 1633041301
          headers: {}
      security:
        - token: []
  /nodes/{node_name}/topics:
    get:
      summary: 获取指定节点下的主题
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: node_name
          in: path
          description: ''
          required: true
          example: status
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  result:
                    type: array
                    items:
                      $ref: '#/components/schemas/topic'
                  pagination:
                    type: object
                    properties:
                      per_page:
                        type: integer
                      total:
                        type: integer
                      pages:
                        type: integer
                    required:
                      - per_page
                      - total
                      - pages
                required:
                  - success
                  - message
                  - result
                  - pagination
              example:
                success: true
                message: Node topics found
                result:
                  - id: 1146865
                    title: 20250721 - Solana 原生代币 SOL 打赏
                    content: "基于 Solana 原生代币的社区内打赏功能已经在 V2EX 部署。\r\n\r\n目前你可以在用户个人主页的桌面版本找到打赏按钮，比如这是我的主页，上面就可以看到打赏按钮：\r\n\r\nhttps://www.v2ex.com/member/Livid\r\n\r\n如果你希望在 V2EX 接受 Solana 打赏，可以在设置中绑定自己的 Solana 钱包地址：\r\n\r\nhttps://www.v2ex.com/settings/crypto\r\n\r\n接下来，这个按钮的功能会扩展到手机版本页面及主题页面。\r\n\r\n这里可以看到自己收到和发出的所有打赏记录：\r\n\r\nhttps://www.v2ex.com/solana/tips\r\n\r\n目前支持的是使用 Solana 原生代币 SOL 直接打赏。使用的是最简单的 transfer 方式，所有数额会 100% 进入被打赏用户的钱包，V2EX 只是提供界面和记录，不收取任何中间费用。\r\n\r\n对于很多初次使用 Solana 的用户，相信这会成为他们获得第一笔 gas 费的来源。\r\n\r\n后续会扩展支持其他 SPL Token 。"
                    content_rendered: >-
                      基于 Solana 原生代币的社区内打赏功能已经在 V2EX 部署。<br /><br
                      />目前你可以在用户个人主页的桌面版本找到打赏按钮，比如这是我的主页，上面就可以看到打赏按钮：<br /><br
                      /><a target="_blank"
                      href="https://www.v2ex.com/member/Livid" rel="nofollow
                      noopener">https://www.v2ex.com/member/Livid</a><br /><br
                      />如果你希望在 V2EX 接受 Solana 打赏，可以在设置中绑定自己的 Solana 钱包地址：<br
                      /><br /><a target="_blank"
                      href="https://www.v2ex.com/settings/crypto" rel="nofollow
                      noopener">https://www.v2ex.com/settings/crypto</a><br
                      /><br />接下来，这个按钮的功能会扩展到手机版本页面及主题页面。<br /><br
                      />这里可以看到自己收到和发出的所有打赏记录：<br /><br /><a target="_blank"
                      href="https://www.v2ex.com/solana/tips" rel="nofollow
                      noopener">https://www.v2ex.com/solana/tips</a><br /><br
                      />目前支持的是使用 Solana 原生代币 SOL 直接打赏。使用的是最简单的 transfer 方式，所有数额会
                      100% 进入被打赏用户的钱包，V2EX 只是提供界面和记录，不收取任何中间费用。<br /><br
                      />对于很多初次使用 Solana 的用户，相信这会成为他们获得第一笔 gas 费的来源。<br /><br
                      />后续会扩展支持其他 SPL Token 。
                    syntax: 0
                    url: https://www.v2ex.com/t/1146865
                    replies: 711
                    last_reply_by: ik
                    created: 1753163305
                    last_modified: 1753163305
                    last_touched: 1753371501
                  - id: 1147010
                    title: 20250722 - Solana 打赏功能更新 1
                    content: "当你访问别人主页时，可以看到你们最近的打赏交互。\r\n\r\n![]( https://i.v2ex.co/R8UewxIK.png)\r\n\r\n在打赏记录页面，可以查看「全部」「我发出的」「我收到的」：\r\n\r\nhttps://www.v2ex.com/solana/tips\r\n\r\n![]( https://i.v2ex.co/byG1Gy6w.png)"
                    content_rendered: >
                      <p>当你访问别人主页时，可以看到你们最近的打赏交互。</p>

                      <p><img alt="" class="embedded_image" loading="lazy"
                      referrerpolicy="no-referrer" rel="noreferrer"
                      src="https://i.v2ex.co/R8UewxIK.png"/></p>

                      <p>在打赏记录页面，可以查看「全部」「我发出的」「我收到的」：</p>

                      <p><a href="https://www.v2ex.com/solana/tips"
                      rel="nofollow">https://www.v2ex.com/solana/tips</a></p>

                      <p><img alt="" class="embedded_image" loading="lazy"
                      referrerpolicy="no-referrer" rel="noreferrer"
                      src="https://i.v2ex.co/byG1Gy6w.png"/></p>
                    syntax: 1
                    url: https://www.v2ex.com/t/1147010
                    replies: 213
                    last_reply_by: KelleyV9
                    created: 1753222186
                    last_modified: 1753222186
                    last_touched: 1753344551
                  - id: 1144985
                    title: 20250713 - Solana 登录和注册支持已经部署并开启
                    content: "现在当你在 V2EX 登录或注册时，会看到全新的 Solana 选项。\r\n\r\n关于 V2EX 对 Solana 的支持：\r\n\r\nhttps://www.v2ex.com/solana\r\n\r\n- 如果你已经有 V2EX 账号，那么你可以通过 Phantom 或者 Glow 钱包连接一个 Solana 地址，然后就可以通过 Phantom 或者 Glow 登录。\r\n- 如果你还没有 V2EX 账号，那么如果持有至少 10000 V2EX Coin ，就可以注册一个新的 V2EX 账号，不需要使用邀请码激活账号。后续在继续使用 V2EX 的互动功能时，地址里也需要一直持有这个数量。\r\n\r\n## Get V2EX Coin\r\n\r\nhttps://pump.fun/coin/9raUVuzeWUk53co63M4WXLWPWE4Xc6Lpn7RS9dnkpump\r\n\r\n---\r\n\r\n后续，会继续基于 Solana 生态，推出更多玩法。\r\n\r\n谢谢大家支持。"
                    content_rendered: >
                      <p>现在当你在 V2EX 登录或注册时，会看到全新的 Solana 选项。</p>

                      <p>关于 V2EX 对 Solana 的支持：</p>

                      <p><a href="https://www.v2ex.com/solana"
                      rel="nofollow">https://www.v2ex.com/solana</a></p>

                      <ul>

                      <li>如果你已经有 V2EX 账号，那么你可以通过 Phantom 或者 Glow 钱包连接一个 Solana
                      地址，然后就可以通过 Phantom 或者 Glow 登录。</li>

                      <li>如果你还没有 V2EX 账号，那么如果持有至少 10000 V2EX Coin ，就可以注册一个新的
                      V2EX 账号，不需要使用邀请码激活账号。后续在继续使用 V2EX
                      的互动功能时，地址里也需要一直持有这个数量。</li>

                      </ul>

                      <h2>Get V2EX Coin</h2>

                      <p><a
                      href="https://pump.fun/coin/9raUVuzeWUk53co63M4WXLWPWE4Xc6Lpn7RS9dnkpump"
                      rel="nofollow">https://pump.fun/coin/9raUVuzeWUk53co63M4WXLWPWE4Xc6Lpn7RS9dnkpump</a></p>

                      <hr/>

                      <p>后续，会继续基于 Solana 生态，推出更多玩法。</p>

                      <p>谢谢大家支持。</p>
                    syntax: 1
                    url: https://www.v2ex.com/t/1144985
                    replies: 143
                    last_reply_by: 0xppp
                    created: 1752455377
                    last_modified: 1752455803
                    last_touched: 1752757500
                  - id: 1140039
                    title: 20250620 - 2FA 开启和关闭时的邮件提醒
                    content: "当你在 V2EX 开启或者关闭两步验证时，现在会收到邮件提醒。\r\n\r\n如果在接下来，你不记得自己做过开启两步验证的操作但是却收到这样的提醒邮件，那么请使用注册邮箱发信到 support@v2ex.com 寻求协助。"
                    content_rendered: >-
                      当你在 V2EX 开启或者关闭两步验证时，现在会收到邮件提醒。<br /><br
                      />如果在接下来，你不记得自己做过开启两步验证的操作但是却收到这样的提醒邮件，那么请使用注册邮箱发信到
                      support@v2ex.com 寻求协助。
                    syntax: 0
                    url: https://www.v2ex.com/t/1140039
                    replies: 4
                    last_reply_by: wessin
                    created: 1750438301
                    last_modified: 1750438301
                    last_touched: 1750449899
                  - id: 1139788
                    title: 20250619 - 10 分钟左右的停服维护
                    content: >-
                      中国时间 6 月 20 日凌晨 1:00-2:00 之间，V2EX 可能会出现最多 10
                      分钟左右的无法访问，因为需要部署一个涉及改表加列的更新。
                    content_rendered: >-
                      中国时间 6 月 20 日凌晨 1:00-2:00 之间，V2EX 可能会出现最多 10
                      分钟左右的无法访问，因为需要部署一个涉及改表加列的更新。
                    syntax: 0
                    url: https://www.v2ex.com/t/1139788
                    replies: 11
                    last_reply_by: Vraw5
                    created: 1750347566
                    last_modified: 1750347566
                    last_touched: 1750376915
                  - id: 1139524
                    title: 20250618 - OTP 输入有时候会失效的问题似乎是修好了
                    content: "之前，在输入两步验证码的时候，在某些极端情况下，连续两次的输入系统都不接受，直到第三次。\r\n\r\n一部分是因为服务器的时钟问题，另外一部分是代码的设置问题。\r\n\r\n最近，在 Sonnet 4 的帮助下，调整了这个地方的一个参数，目前看起来已经不会出现这样的情况了。"
                    content_rendered: >-
                      之前，在输入两步验证码的时候，在某些极端情况下，连续两次的输入系统都不接受，直到第三次。<br /><br
                      />一部分是因为服务器的时钟问题，另外一部分是代码的设置问题。<br /><br />最近，在 Sonnet 4
                      的帮助下，调整了这个地方的一个参数，目前看起来已经不会出现这样的情况了。
                    syntax: 0
                    url: https://www.v2ex.com/t/1139524
                    replies: 0
                    last_reply_by: ''
                    created: 1750249899
                    last_modified: 1750249899
                    last_touched: 1750249899
                  - id: 1037849
                    title: 20240505 - 邀请码系统
                    content: "我真的非常感谢那些在帮助处理 spam 的朋友们。但是，这种事情说真的，并不是一件愉快的事情，并不是一件做得越多越开心的事情。在任何更大的互联网产品里，内容审核可能都是最痛苦的工作之一。\r\n\r\n所以，最近在思考了一段时间之后，决定：\r\n\r\n从 id>688500 （或者某个更大的数字，因为逻辑还需要一些测试）开始，新账号在开始使用之前，需要使用一个邀请码激活。\r\n\r\n邀请码需要老用户用铜币生成。\r\n\r\n大部分的 spam 及破坏行为，都是一些注册时间非常新的账号所带来的。所以希望这个新办法可以让社区里不愉快部分减少，无论是对于用户还是管理员们。\r\n\r\n另外就是，如果你想退出这个社区，可以在这个帖子下面留言，我看到就会处理。谢谢。\r\n\r\n如果能够降低毒性，让愉快的部分变多，才会是这里能够继续长久存在下去的基础。否则，为什么要继续维护痛苦呢？"
                    content_rendered: >-
                      我真的非常感谢那些在帮助处理 spam
                      的朋友们。但是，这种事情说真的，并不是一件愉快的事情，并不是一件做得越多越开心的事情。在任何更大的互联网产品里，内容审核可能都是最痛苦的工作之一。<br
                      /><br />所以，最近在思考了一段时间之后，决定：<br /><br />从 id&gt;688500
                      （或者某个更大的数字，因为逻辑还需要一些测试）开始，新账号在开始使用之前，需要使用一个邀请码激活。<br /><br
                      />邀请码需要老用户用铜币生成。<br /><br />大部分的 spam
                      及破坏行为，都是一些注册时间非常新的账号所带来的。所以希望这个新办法可以让社区里不愉快部分减少，无论是对于用户还是管理员们。<br
                      /><br />另外就是，如果你想退出这个社区，可以在这个帖子下面留言，我看到就会处理。谢谢。<br /><br
                      />如果能够降低毒性，让愉快的部分变多，才会是这里能够继续长久存在下去的基础。否则，为什么要继续维护痛苦呢？
                    syntax: 0
                    url: https://www.v2ex.com/t/1037849
                    replies: 488
                    last_reply_by: xmz8888
                    created: 1714910588
                    last_modified: 1714910615
                    last_touched: 1739726398
                  - id: 1101310
                    title: 20241230 - vLLM + Qwen2.5-Coder-32B-Instruct 驱动的新的标签系统
                    content: "V2EX 除了节点之外，也会根据主题内容生成 3 个 tag 。\r\n\r\n之前这个系统用的是 Boson NLP 提供的服务，不过他们后来停止了这个 API 服务。\r\n\r\n然后这件事情就搁置了一段时间。\r\n\r\n最近用 vLLM 部署了 Qwen2.5-Coder-32B-Instruct ，然后尝试用 prompt 的方式来为主题生成标签。虽然某些时候会产生无限循环，但是大部分情况下效果很不错。\r\n\r\n目前大概 2 - 3 秒可以分析完一个主题并生成 3 个 tag 。"
                    content_rendered: >-
                      V2EX 除了节点之外，也会根据主题内容生成 3 个 tag 。<br /><br />之前这个系统用的是
                      Boson NLP 提供的服务，不过他们后来停止了这个 API 服务。<br /><br
                      />然后这件事情就搁置了一段时间。<br /><br />最近用 vLLM 部署了
                      Qwen2.5-Coder-32B-Instruct ，然后尝试用 prompt
                      的方式来为主题生成标签。虽然某些时候会产生无限循环，但是大部分情况下效果很不错。<br /><br />目前大概 2
                      - 3 秒可以分析完一个主题并生成 3 个 tag 。
                    syntax: 0
                    url: https://www.v2ex.com/t/1101310
                    replies: 13
                    last_reply_by: musi
                    created: 1735547703
                    last_modified: 1735547703
                    last_touched: 1735813638
                  - id: 939886
                    title: 20230514 - 关于主题分页 502 问题的进一步进展
                    content: "在之前 20230509 的部署中，去掉了后端可能会导致问题的一个跳转：\r\n\r\nhttps://www.v2ex.com/t/938867\r\n\r\n但是那样会带来的一个副作用是，网站无法再记住和跳转到你最后访问过的主题页数。\r\n\r\n在今天的部署中，使用了浏览器的 Local Storage 来记住和使用页码，这样当你访问像下面这样的需要分页的主题时，网站的各种列表中会记住和使用你最后的页码。\r\n\r\nhttps://www.v2ex.com/t/939486?p=2"
                    content_rendered: >-
                      在之前 20230509 的部署中，去掉了后端可能会导致问题的一个跳转：<br /><br /><a
                      target="_blank" href="https://www.v2ex.com/t/938867"
                      rel="nofollow
                      noopener">https://www.v2ex.com/t/938867</a><br /><br
                      />但是那样会带来的一个副作用是，网站无法再记住和跳转到你最后访问过的主题页数。<br /><br
                      />在今天的部署中，使用了浏览器的 Local Storage
                      来记住和使用页码，这样当你访问像下面这样的需要分页的主题时，网站的各种列表中会记住和使用你最后的页码。<br
                      /><br /><a target="_blank"
                      href="https://www.v2ex.com/t/939486?p=2" rel="nofollow
                      noopener">https://www.v2ex.com/t/939486?p=2</a>
                    syntax: 0
                    url: https://www.v2ex.com/t/939886
                    replies: 0
                    last_reply_by: ''
                    created: 1684050976
                    last_modified: 1684050976
                    last_touched: 1686110850
                  - id: 938867
                    title: 20230509 - 关于部分用户在访问需要翻页的主题时遇到的 502 问题
                    content: "和分页有关的一个跳转及 cookie 逻辑在 20230509 的部署中已经去掉，希望对解决这个问题有帮助。\r\n\r\n谢谢大家之前的反馈。"
                    content_rendered: >-
                      和分页有关的一个跳转及 cookie 逻辑在 20230509 的部署中已经去掉，希望对解决这个问题有帮助。<br
                      /><br />谢谢大家之前的反馈。
                    syntax: 0
                    url: https://www.v2ex.com/t/938867
                    replies: 23
                    last_reply_by: BlackAndBlue
                    created: 1683696198
                    last_modified: 1683696198
                    last_touched: 1683726510
                  - id: 918918
                    title: 20230224 - 正在修复队列系统的一个问题
                    content: 大家的反馈我已经收到，目前提醒系统确实存在一些问题。
                    content_rendered: |
                      <p>大家的反馈我已经收到，目前提醒系统确实存在一些问题。</p>
                    syntax: 1
                    url: https://www.v2ex.com/t/918918
                    replies: 27
                    last_reply_by: julyclyde
                    created: 1677227293
                    last_modified: 1677227293
                    last_touched: 1677400646
                  - id: 819434
                    title: 20211201 - 在回复列表的用户名旁增加了楼主（OP）标注
                    content: ''
                    content_rendered: ''
                    syntax: 0
                    url: https://www.v2ex.com/t/819434
                    replies: 13
                    last_reply_by: MaiKuraki
                    created: 1638395875
                    last_modified: 1638395875
                    last_touched: 1639079193
                  - id: 821011
                    title: 20211208 - 创建新主题时的草稿问题
                    content: "你可能会发现在创建完新主题之后，下一次创建新主题时，上一次的内容依然出现在草稿内容中。\r\n\r\n导致这个问题的后端修复已经部署。"
                    content_rendered: >-
                      你可能会发现在创建完新主题之后，下一次创建新主题时，上一次的内容依然出现在草稿内容中。<br /><br
                      />导致这个问题的后端修复已经部署。
                    syntax: 0
                    url: https://www.v2ex.com/t/821011
                    replies: 0
                    last_reply_by: ''
                    created: 1638992405
                    last_modified: 1638992405
                    last_touched: 1638992405
                  - id: 821014
                    title: 20211208 - 大约持续了 3 个小时的头像上传问题
                    content: "由于测试中缺少一个环节，导致一个没有正确工作的 Remote Worker 的 Docker image 被部署，由此导致了大约持续 3 个小时的头像上传处理失败。\r\n\r\n最近我们在把后端用于处理头像上传的组件进行一些现代化改造，并且在 GitHub 上开源了这个项目的进展：\r\n\r\nhttps://github.com/v2ex/remote\r\n\r\n目前 V2EX 的头像上传可以支持以下格式：\r\n\r\n- PNG\r\n- JPEG\r\n- JPEG 2000\r\n- GIF\r\n- WEBP\r\n- TIFF\r\n- BMP\r\n- ICNS\r\n- ICO\r\n- AVIF\r\n- HEIC\r\n- PSD\r\n- SVG"
                    content_rendered: >
                      <p>由于测试中缺少一个环节，导致一个没有正确工作的 Remote Worker 的 Docker image
                      被部署，由此导致了大约持续 3 个小时的头像上传处理失败。</p>

                      <p>最近我们在把后端用于处理头像上传的组件进行一些现代化改造，并且在 GitHub
                      上开源了这个项目的进展：</p>

                      <p><a href="https://github.com/v2ex/remote"
                      rel="nofollow">https://github.com/v2ex/remote</a></p>

                      <p>目前 V2EX 的头像上传可以支持以下格式：</p>

                      <ul>

                      <li>PNG</li>

                      <li>JPEG</li>

                      <li>JPEG 2000</li>

                      <li>GIF</li>

                      <li>WEBP</li>

                      <li>TIFF</li>

                      <li>BMP</li>

                      <li>ICNS</li>

                      <li>ICO</li>

                      <li>AVIF</li>

                      <li>HEIC</li>

                      <li>PSD</li>

                      <li>SVG</li>

                      </ul>
                    syntax: 1
                    url: https://www.v2ex.com/t/821014
                    replies: 0
                    last_reply_by: ''
                    created: 1638996908
                    last_modified: 1638996919
                    last_touched: 1638910508
                  - id: 805755
                    title: 20211003 - 修复了由于 webfont 引起的页面显示延迟
                    content: "通过 web.dev 的扫描结果，进而学习到了 `font-display: swap` 这个新属性的用法，分享给大家 :)\r\n\r\nhttps://web.dev/font-display/"
                    content_rendered: >
                      <p>通过 web.dev 的扫描结果，进而学习到了 <code>font-display: swap</code>
                      这个新属性的用法，分享给大家 :)</p>

                      <p><a href="https://web.dev/font-display/"
                      rel="nofollow">https://web.dev/font-display/</a></p>
                    syntax: 1
                    url: https://www.v2ex.com/t/805755
                    replies: 7
                    last_reply_by: admonition
                    created: 1633245082
                    last_modified: 1633245121
                    last_touched: 1633303199
                  - id: 805511
                    title: 20211001 - 新功能 - 最近访问过的主题
                    content: "现在在桌面版的首页右侧，会显示自己最近访问过的 5 个主题。在这个功能模块的右上角，按一下清除就可以把它清除掉。\r\n\r\nhttps://i.v2ex.co/Cl15Uef4.png"
                    content_rendered: >-
                      现在在桌面版的首页右侧，会显示自己最近访问过的 5
                      个主题。在这个功能模块的右上角，按一下清除就可以把它清除掉。<br /><br /><a
                      target="_blank" href="/i/Cl15Uef4.png" rel="nofollow
                      noopener" target="_blank" title="在新窗口打开图片
                      Cl15Uef4.png"><img src="//i.v2ex.co/Cl15Uef4.png"
                      class="embedded_image"></a>
                    syntax: 0
                    url: https://www.v2ex.com/t/805511
                    replies: 10
                    last_reply_by: v2exblog
                    created: 1633041740
                    last_modified: 1633041740
                    last_touched: 1633187140
                  - id: 805624
                    title: 20211002 - 修复了记事本编辑框的自适应高度问题
                    content: "谢谢 @ray1980 https://www.v2ex.com/t/799581 和 @katsusan https://www.v2ex.com/t/803512 的反馈。\r\n\r\n记事本功能之前发生的自适应高度问题已经修复。同时对样式进行了一些微调。\r\n\r\nhttps://www.v2ex.com/notes"
                    content_rendered: >-
                      谢谢 @<a target="_blank" href="/member/ray1980"
                      rel="nofollow noopener">ray1980</a> <a target="_blank"
                      href="https://www.v2ex.com/t/799581" rel="nofollow
                      noopener">https://www.v2ex.com/t/799581</a> 和 @<a
                      target="_blank" href="/member/katsusan" rel="nofollow
                      noopener">katsusan</a> <a target="_blank"
                      href="https://www.v2ex.com/t/803512" rel="nofollow
                      noopener">https://www.v2ex.com/t/803512</a> 的反馈。<br /><br
                      />记事本功能之前发生的自适应高度问题已经修复。同时对样式进行了一些微调。<br /><br /><a
                      target="_blank" href="https://www.v2ex.com/notes"
                      rel="nofollow noopener">https://www.v2ex.com/notes</a>
                    syntax: 0
                    url: https://www.v2ex.com/t/805624
                    replies: 3
                    last_reply_by: Livid
                    created: 1633128461
                    last_modified: 1633128461
                    last_touched: 1633186189
                  - id: 651795
                    title: 20200310 - 大约持续了 12 分钟的一个故障
                    content: "https://i.v2ex.co/6ouLmz4C.png\r\n\r\n登录用户在部分页面上会遇到 500 错误或者看到 Cloudflare 的 502 错误。大约持续了 12 分钟。现在已经修复。"
                    content_rendered: >-
                      <a target="_blank" href="/i/6ouLmz4C.png" rel="nofollow
                      noopener" target="_blank" title="在新窗口打开图片
                      6ouLmz4C.png"><img src="//i.v2ex.co/6ouLmz4C.png"
                      class="embedded_image"></a><br /><br />登录用户在部分页面上会遇到 500
                      错误或者看到 Cloudflare 的 502 错误。大约持续了 12 分钟。现在已经修复。
                    syntax: 0
                    url: https://www.v2ex.com/t/651795
                    replies: 9
                    last_reply_by: masy
                    created: 1583897113
                    last_modified: 1583897113
                    last_touched: 1583928344
                  - id: 580480
                    title: 20190706 - 关于最近基础架构方面的一些变动
                    content: "因为方便进行技术更新方面的原因（本站目前唯一的开发者 @Livid 在美国），所以前段时间将网站的服务器和 CDN 迁往了美国。因为没有继续使用中国大陆的服务器和 CDN，所以目前网站在服务中国大陆境内的访问者时，速度会有下降，同时也就失去了中国的 ICP 备案号码。\r\n\r\n没有必要对这件事情做过度解读，我觉得很累，只是想在本地时区能够正常睡觉而已。\r\n\r\n谢谢大家。\r\n\r\n---\r\n\r\n### On recent change of this website's infrastructure\r\n\r\nFor easier updating the code of this site, as the sole developer based in the U.S., I moved the server and CDN of this website to California. Since China infrastructure is no longer part of the site, loading performance may degrade for visitors from China mainland. Also, this website is no longer eligible for China's ICP filing.\r\n\r\nNo need to over-interpret this. I'm tired. Just want to have a good sleep in local timezone.\r\n\r\nThanks."
                    content_rendered: >
                      <p>因为方便进行技术更新方面的原因（本站目前唯一的开发者 @<a
                      href="/member/Livid">Livid</a> 在美国），所以前段时间将网站的服务器和 CDN
                      迁往了美国。因为没有继续使用中国大陆的服务器和
                      CDN，所以目前网站在服务中国大陆境内的访问者时，速度会有下降，同时也就失去了中国的 ICP 备案号码。</p>

                      <p>没有必要对这件事情做过度解读，我觉得很累，只是想在本地时区能够正常睡觉而已。</p>

                      <p>谢谢大家。</p>

                      <hr/>

                      <h3>On recent change of this website's infrastructure</h3>

                      <p>For easier updating the code of this site, as the sole
                      developer based in the U.S., I moved the server and CDN of
                      this website to California. Since China infrastructure is
                      no longer part of the site, loading performance may
                      degrade for visitors from China mainland. Also, this
                      website is no longer eligible for China's ICP filing.</p>

                      <p>No need to over-interpret this. I'm tired. Just want to
                      have a good sleep in local timezone.</p>

                      <p>Thanks.</p>
                    syntax: 1
                    url: https://www.v2ex.com/t/580480
                    replies: 207
                    last_reply_by: KrisLiu
                    created: 1562342583
                    last_modified: 1607782803
                    last_touched: 1572266810
                  - id: 610900
                    title: 20191019 - 关于 Light Mode 的样式问题
                    content: "下面这个主题中所反馈的 Light Mode 中缺乏分割线的样式问题，是最近在逐步启用 CSS Variable 中人为失误造成的一个问题。现在已经修复。\r\n\r\nhttps://www.v2ex.com/t/610859\r\n\r\n谢谢大家的反馈。\r\n\r\n另外就是，如果你还没有试过，那么在桌面版本的右上角，多了一个新的样式切换按钮，可以将全站样式在 Light/Dark 模式之间手动切换。"
                    content_rendered: >-
                      下面这个主题中所反馈的 Light Mode 中缺乏分割线的样式问题，是最近在逐步启用 CSS Variable
                      中人为失误造成的一个问题。现在已经修复。<br /><br /><a target="_blank"
                      href="https://www.v2ex.com/t/610859"
                      rel="nofollow">https://www.v2ex.com/t/610859</a><br /><br
                      />谢谢大家的反馈。<br /><br
                      />另外就是，如果你还没有试过，那么在桌面版本的右上角，多了一个新的样式切换按钮，可以将全站样式在
                      Light/Dark 模式之间手动切换。
                    syntax: 0
                    url: https://www.v2ex.com/t/610900
                    replies: 55
                    last_reply_by: Livid
                    created: 1571457964
                    last_modified: 1571457964
                    last_touched: 1571700919
                pagination:
                  per_page: 20
                  total: 39
                  pages: 2
          headers: {}
      security:
        - token: []
webhooks: {}
components:
  schemas:
    topic:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        content_rendered:
          type: string
        syntax:
          type: integer
        url:
          type: string
        replies:
          type: integer
        last_reply_by:
          type: string
        created:
          type: integer
        last_modified:
          type: integer
        last_touched:
          type: integer
        member:
          properties:
            id:
              type: integer
            username:
              type: string
            bio:
              type: string
            website:
              type: string
            github:
              type: string
            url:
              type: string
            avatar:
              type: string
            created:
              type: integer
            pro:
              type: integer
          required:
            - id
            - username
            - bio
            - website
            - github
            - url
            - avatar
            - created
            - pro
          $ref: '#/components/schemas/member'
        node:
          $ref: '#/components/schemas/node'
        supplements:
          type: array
          items:
            properties:
              id:
                type: integer
              content:
                type: string
              content_rendered:
                type: string
              syntax:
                type: integer
              created:
                type: integer
            $ref: '#/components/schemas/supplement'
      required:
        - id
        - title
        - content
        - content_rendered
        - syntax
        - url
        - replies
        - last_reply_by
        - created
        - last_modified
        - last_touched
        - member
        - node
        - supplements
      title: 主题
    reply:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        content_rendered:
          type: string
        created:
          type: integer
        member:
          $ref: '#/components/schemas/member'
      required:
        - id
        - content
        - content_rendered
        - created
        - member
      title: 回复
    node:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        name:
          type: string
        title:
          type: string
        header:
          type: string
        footer:
          type: string
        avatar:
          type: string
        topics:
          type: integer
        created:
          type: integer
        last_modified:
          type: integer
      required:
        - id
        - url
        - name
        - title
        - header
        - footer
        - avatar
        - topics
        - created
        - last_modified
      title: 节点
    member:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        bio:
          type: string
        website:
          type: string
        github:
          type: string
        url:
          type: string
        avatar:
          type: string
        created:
          type: integer
        pro:
          type: integer
      required:
        - id
        - username
        - bio
        - website
        - github
        - url
        - avatar
        - created
        - pro
      title: 用户
    supplement:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        content_rendered:
          type: string
        syntax:
          type: integer
        created:
          type: integer
      title: 附言
  securitySchemes:
    token:
      type: http
      scheme: bearer
servers:
  - url: https://www.v2ex.com/api/v2
    description: 正式环境
security:
  - token: []
